### ISSUE TITLE
RN 0.4.0 support for IOS

### ISSUE THREAD

**Issue by jjdp** [makemoji/Makemoji-React-Native#1]
see breaking changes for iOS native headers
[https://github.com/facebook/react-native/releases/tag/v0.40.0](https://github.com/facebook/react-native/releases/tag/v0.40.0)

@sbaar

**Comment by sbaar** [comment]
Thanks for reporting this. The library is due for a big update in a few weeks and this will be part of it.

**Comment by jjdp** [comment]
also if you are planning to update the example app to RN 0.41.0, it needs a one liner change in MainApplication.java

see [https://github.com/facebook/react-native/commit/f3c8158773edf418833ff0032414433edbc6cd62](https://github.com/facebook/react-native/commit/f3c8158773edf418833ff0032414433edbc6cd62)

**Comment by jjdp** [comment]
what's the status?

**Comment by sbaar** [comment]
No eta at the moment. @jjdp Are you planning on using this library?

**Comment by jjdp** [comment]
yes i can fork it in the meantime

**Comment by sbaar** [comment]
@jjdp The library has been updated for rn 43. Thank you for your patience!
